/**:
   ros__parameters:
    image_transport: raw
    family: 25h9
    size: 0.03
    max_hamming: 0

    detector:
        threads: 1
        decimate: 2.0
        blur: 0.0
        refine: 1
        sharpening: 0.25
        debug: 0

    tag:
        ids: [0, 1]
        frames: [base, object]
        sizes: [0.03, 0.03]
